services:
  web:
    build: .
    volumes:
      - .:.
    ports:
      - 9222:9222
    tty: true
  chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: 2gb
    depends_on:
      - web
    ports:
      - "4444:4444"
      - "7900:7900"
